# Font
font_family      Noto Serif
font_size        10.0

# Yellow text for what you type (foreground)
foreground       #E8E8E8
background       #1E1E20

# Transparency
background_opacity 0.72

# Padding
window_padding_width 16

# Remove title bar decorations
hide_window_decorations yes

# Cursor
cursor_shape     beam
cursor           #FFDC32

# Selection color
selection_foreground #1E1E20
selection_background #FFDC32

# No bell
enable_audio_bell no

# Scrollback
scrollback_lines 10000
symbol_map U+E000-U+F8FF,U+F0000-U+FFFFF Symbols Nerd Font
